### ISSUE TITLE
I'm trying the bot on docker but I'm having problems

### ISSUE THREAD

**Issue by theRAGEhero** [LucaTNT/telegram-bot-amazon#18]
Hello Luca, thank you for this bot!

I tried to use the docker image, I've changed the bot taken from botfather, the amazon code and the amazon nationality. 

`docker run -e TELEGRAM_BOT_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -e AMAZON_TAG=Codice00-21 -e AMAZON_TLD=it --init lucatnt/telegram-bot-amazon
`
I can see this log for the container created.

`Mon, 08 Mar 2021 18:25:59 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.

In the future, you will have to enable it yourself.

See https://github.com/yagop/node-telegram-bot-api/issues/319. at node:internal/modules/cjs/loader:1108:14

Missing GROUP_REPLACEMENT_MESSAGE env variable, using the default one`

If I write privately to the bot he doesn't reply. 

Do I have to do anything after running the container?

ps. Does the bot work in channels? Does it work with a previous affiliated link?

Thank you!
Alessandro

**Comment by LucaTNT** [comment]
Hi Alessandro!

> ```
Mon, 08 Mar 2021 18:25:59 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See yagop/node-telegram-bot-api#319. at node:internal/modules/cjs/loader:1108:14
Missing GROUP_REPLACEMENT_MESSAGE env variable, using the default one
```
This is normal, don't worry about it. You can, however, supply the `GROUP_REPLACEMENT_MESSAGE` as documented in the README file if you'd like. 

> If I write privately to the bot he doesn't reply.
> 
> Do I have to do anything after running the container?

It should just start running, are you sure the bot token is correct?

> ps. Does the bot work in channels? Does it work with a previous affiliated link?
Yes (it deletes the original message, then it re-posts it according to `GROUP_REPLACEMENT_MESSAGE`) and yes.

**Comment by theRAGEhero** [comment]
Hi Luca, thank you for your quick reply.

I've tried again to do everything from start and it works. I don't know why yesterday it wasn't.

Thank you again, I'll leave my docker-compose.yml file in case someone needs it.

```
version: '3.3'
services:
    telegram-bot-amazon:
        environment:
            - TELEGRAM_BOT_TOKEN=xxxxxxxxxxxxxx
            - AMAZON_TAG=myCode00-21
            - AMAZON_TLD=it
            - GROUP_REPLACEMENT_MESSAGE=Message by {USER} with Amazon affiliate link:\n\n{MESSAGE}
           # - SHORTEN_LINKS=true
           # - BITLY_TOKEN=
        image: lucatnt/telegram-bot-amazon
```
